
#line 3 "lex.prlc_.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer prlc__create_buffer
#define yy_delete_buffer prlc__delete_buffer
#define yy_flex_debug prlc__flex_debug
#define yy_init_buffer prlc__init_buffer
#define yy_flush_buffer prlc__flush_buffer
#define yy_load_buffer_state prlc__load_buffer_state
#define yy_switch_to_buffer prlc__switch_to_buffer
#define yyin prlc_in
#define yyleng prlc_leng
#define yylex prlc_lex
#define yylineno prlc_lineno
#define yyout prlc_out
#define yyrestart prlc_restart
#define yytext prlc_text
#define yywrap prlc_wrap
#define yyalloc prlc_alloc
#define yyrealloc prlc_realloc
#define yyfree prlc_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
typedef uint64_t flex_uint64_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE prlc_restart(prlc_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t prlc_leng;

extern FILE *prlc_in, *prlc_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE prlc_lex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-prlc_lineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                yy_size_t yyl;\
                for ( yyl = n; yyl < prlc_leng; ++yyl )\
                    if ( prlc_text[yyl] == '\n' )\
                        --prlc_lineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up prlc_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up prlc_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via prlc_restart()), so that the user can continue scanning by
	 * just pointing prlc_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when prlc_text is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t prlc_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow prlc_wrap()'s to do buffer switches
 * instead of setting up a fresh prlc_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void prlc_restart (FILE *input_file  );
void prlc__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE prlc__create_buffer (FILE *file,int size  );
void prlc__delete_buffer (YY_BUFFER_STATE b  );
void prlc__flush_buffer (YY_BUFFER_STATE b  );
void prlc_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void prlc_pop_buffer_state (void );

static void prlc_ensure_buffer_stack (void );
static void prlc__load_buffer_state (void );
static void prlc__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER prlc__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE prlc__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE prlc__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE prlc__scan_bytes (yyconst char *bytes,yy_size_t len  );

void *prlc_alloc (yy_size_t  );
void *prlc_realloc (void *,yy_size_t  );
void prlc_free (void *  );

#define yy_new_buffer prlc__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        prlc_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            prlc__create_buffer(prlc_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        prlc_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            prlc__create_buffer(prlc_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define prlc_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *prlc_in = (FILE *) 0, *prlc_out = (FILE *) 0;

typedef int yy_state_type;

extern int prlc_lineno;

int prlc_lineno = 1;

extern char *prlc_text;
#define yytext_ptr prlc_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up prlc_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	prlc_leng = (yy_size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 50
#define YY_END_OF_BUFFER 51
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[132] =
    {   0,
       48,   48,   51,   49,   48,   48,   41,   32,   36,    1,
       46,   33,   37,   39,   28,   29,   38,   49,   34,   35,
       17,   17,   45,   31,   47,   30,   42,   16,   43,   44,
       15,   15,   15,   15,   15,   27,   40,   48,   10,    0,
       12,    0,    0,   13,   13,   13,    1,    0,    0,   17,
       17,    0,    0,    0,    0,    0,   17,   22,    0,   21,
       16,   15,   15,   15,   15,   15,   15,   25,   24,   14,
       13,   13,   13,   11,    0,    0,    0,   17,   26,    0,
        0,   19,   18,    0,   19,   19,   20,   23,    6,   15,
        5,   15,   15,   14,    4,    2,    3,   19,   18,    0,

       19,   19,    0,    0,    1,   18,   19,   19,   19,   15,
       15,   15,   18,   19,   19,   19,   19,   15,   15,   15,
       19,   15,   15,    9,   15,    7,   15,   15,   15,    8,
        0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   22,    7,   23,
       24,   25,   26,    7,   27,   27,   27,   27,   28,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       27,   27,   27,   27,   27,   27,   27,   27,   27,   27,
       29,   30,   31,    7,   32,    7,   33,   33,   34,   35,

       36,   37,   33,   33,   38,   33,   33,   39,   33,   40,
       41,   42,   43,   44,   45,   46,   47,   33,   33,   33,
       33,   33,    7,   48,    7,   49,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[50] =
    {   0,
        1,    1,    2,    3,    3,    3,    3,    4,    3,    3,
        5,    3,    3,    3,    3,    3,    3,    3,    3,    6,
        6,    3,    3,    3,    3,    3,    6,    6,    3,    3,
        3,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    3,    3
    } ;

static yyconst flex_int16_t yy_base[143] =
    {   0,
        0,    0,  247,  248,   48,   51,  222,   50,   49,    0,
      248,  215,  248,  248,  248,   38,  248,   43,  248,  230,
       43,   48,  248,   41,  218,  248,  248,    0,  248,  248,
        0,  202,  205,  199,   30,  248,   62,   85,  248,   68,
      248,   69,    0,    0,  199,  197,    0,   66,   67,   73,
       84,  212,  222,   61,  214,   96,  103,  209,  208,  248,
        0,    0,  195,  186,  193,  195,  181,  248,  248,    0,
        0,  190,   48,  248,   86,  205,  112,  116,  248,  211,
       81,  120,   94,   98,  248,  105,  248,  248,    0,  190,
        0,  184,  181,    0,    0,    0,    0,  122,  125,  133,

      248,  139,  183,  143,  248,  143,  248,  145,  147,  145,
      139,  139,  149,  248,  151,  153,  155,  123,  120,  115,
      157,  107,  111,    0,   92,    0,   92,   87,   68,    0,
      248,  176,  180,  187,  192,  194,  196,   86,  198,  205,
      207,  214
    } ;

static yyconst flex_int16_t yy_def[143] =
    {   0,
      131,    1,  131,  131,  131,  131,  131,  132,  133,  134,
      131,  135,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  136,  131,  131,
      137,  137,  137,  137,  137,  131,  131,  131,  131,  132,
      131,  131,  138,  139,  139,  139,  134,  135,  131,  131,
      131,  131,  140,  131,  131,  131,  131,  131,  131,  131,
      136,  137,  137,  137,  137,  137,  137,  131,  131,  141,
      139,  139,  139,  131,  131,  131,  131,  131,  131,  140,
      142,  131,  131,  131,  131,  131,  131,  131,  137,  137,
      137,  137,  137,  141,  139,  139,  139,  131,  131,  131,

      131,  131,  140,  142,  131,  131,  131,  131,  131,  137,
      137,  137,  131,  131,  131,  131,  131,  137,  137,  137,
      131,  137,  137,  137,  137,  137,  137,  137,  137,  137,
        0,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131
    } ;

static yyconst flex_int16_t yy_nxt[298] =
    {   0,
        4,    5,    6,    5,    7,    8,    4,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   28,   29,    4,
       30,    4,   31,   32,   33,   31,   34,   35,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   36,   37,   38,
       38,   38,   38,   38,   38,   41,   43,   50,   51,   52,
       54,   55,   50,   51,   58,   54,   55,   57,   57,   66,
       56,   68,   67,   41,   40,   56,   74,   48,   56,   42,
       82,   82,   45,   56,   96,   46,   38,   38,   38,   59,
       75,   76,   70,   97,  104,   49,   48,   42,   40,  105,

       77,   75,   76,   78,   78,   98,   98,  130,   77,   69,
       84,   77,   84,  106,  106,   85,   86,  107,  108,   77,
       54,   55,   57,   57,  109,  109,  100,  129,  100,  128,
       56,  101,  102,   75,   76,   78,   78,  127,   56,   82,
       82,   98,   98,   77,  113,  113,  126,   56,  125,   77,
      124,   77,  114,  115,  123,   56,  104,   77,  116,  116,
      122,  105,  106,  106,  117,  117,  109,  109,  113,  113,
      121,  121,  116,  116,  117,  117,  121,  121,   40,   40,
       40,   40,   40,   44,  120,  119,   44,   47,  118,   47,
       47,   47,   47,   47,   48,   48,   81,   48,   48,   61,

       61,   62,   62,   71,   71,   80,   80,   80,   80,   80,
       80,   80,   94,   94,  103,  103,  103,  103,  103,  103,
      103,  112,  111,  110,   81,   99,   95,   93,   92,   91,
       90,   89,   88,   87,   83,   81,   79,   73,   72,   65,
       64,   63,   60,   53,   49,   39,  131,    3,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131

    } ;

static yyconst flex_int16_t yy_chk[298] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    5,
        5,    5,    6,    6,    6,    8,    9,   16,   16,   18,
       21,   21,   18,   18,   24,   22,   22,   22,   22,   35,
       21,   37,   35,   40,   42,   22,   48,   49,   21,    8,
       54,   54,    9,   22,   73,    9,   38,   38,   38,   24,
       50,   50,  138,   73,   81,   48,   49,   40,   42,   81,

       50,   51,   51,   51,   51,   75,   75,  129,   50,   37,
       56,   51,   56,   83,   83,   56,   56,   84,   84,   51,
       57,   57,   57,   57,   86,   86,   77,  128,   77,  127,
       57,   77,   77,   78,   78,   78,   78,  125,   57,   82,
       82,   98,   98,   78,   99,   99,  123,   82,  122,   98,
      120,   78,  100,  100,  119,   82,  104,   98,  102,  102,
      118,  104,  106,  106,  108,  108,  109,  109,  113,  113,
      115,  115,  116,  116,  117,  117,  121,  121,  132,  132,
      132,  132,  132,  133,  112,  111,  133,  134,  110,  134,
      134,  134,  134,  134,  135,  135,  103,  135,  135,  136,

      136,  137,  137,  139,  139,  140,  140,  140,  140,  140,
      140,  140,  141,  141,  142,  142,  142,  142,  142,  142,
      142,   93,   92,   90,   80,   76,   72,   67,   66,   65,
       64,   63,   59,   58,   55,   53,   52,   46,   45,   34,
       33,   32,   25,   20,   12,    7,    3,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131,  131,  131,  131,
      131,  131,  131,  131,  131,  131,  131

    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[51] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int prlc__flex_debug;
int prlc__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *prlc_text;
#line 1 "CSources/PrlcLexer.l"
/*  Created by Alexander Maringele.
    Copyright (c) 2015 Alexander Maringele. All rights reserved.
*/
#line 6 "CSources/PrlcLexer.l"
    
    //  Created by Alexander Maringele.
    //  Copyright (c) 2015 Alexander Maringele. All rights reserved.
    //

#import "CSources/PrlcParser.h"
#import "CSources/PrlcMacros.h"
#import "PrlcParser.tab.h"

#define TOKEN(k)    { return k; }
#define TSTRING(k)  { prlc_lval.cstring = prlc_text; return k; }
#define TNUMBER     { prlc_lval.number = atol(prlc_text); return NUMBER; }
#define TINTEGER 	TSTRING(INTEGER)
#define	TRATIONAL	TSTRING(RATIONAL)
#define TREAL		TSTRING(REAL)

/* to avoid warning: ‘yyunput’ defined but not used */
/* to avoid warning: ‘input’ defined but not used */
#define YY_NO_INPUT 1
/* for the use of multiple lexers (and parsers) */
/* similar to -P prlc_ (lex) */
/*
 %----Rules from her on down are for defining tokens (terminal symbols) of the
 %----grammar, assuming they will be recognized by a lexical scanner.
 %----A ::- rule defines a token, a ::: rule defines a macro that is not a
 %----token. Usual regexp notation is used. ...
 */
/*---- Tokens used in syntax, and cannot be character classes */
/*---- Numbers. Symbols are made part of the same token here. */
/*---- Character classes */
/*---- Space and visible characters upto ~, except ' and \ */
#line 639 "lex.prlc_.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int prlc_lex_destroy (void );

int prlc_get_debug (void );

void prlc_set_debug (int debug_flag  );

YY_EXTRA_TYPE prlc_get_extra (void );

void prlc_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *prlc_get_in (void );

void prlc_set_in  (FILE * in_str  );

FILE *prlc_get_out (void );

void prlc_set_out  (FILE * out_str  );

yy_size_t prlc_get_leng (void );

char *prlc_get_text (void );

int prlc_get_lineno (void );

void prlc_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int prlc_wrap (void );
#else
extern int prlc_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( prlc_text, prlc_leng, 1, prlc_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		yy_size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( prlc_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( prlc_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, prlc_in))==0 && ferror(prlc_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(prlc_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int prlc_lex (void);

#define YY_DECL int prlc_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after prlc_text and prlc_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 101 "CSources/PrlcLexer.l"


#line 822 "lex.prlc_.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! prlc_in )
			prlc_in = stdin;

		if ( ! prlc_out )
			prlc_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			prlc_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				prlc__create_buffer(prlc_in,YY_BUF_SIZE );
		}

		prlc__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of prlc_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 132 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 248 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < prlc_leng; ++yyl )
				if ( prlc_text[yyl] == '\n' )
					   
    prlc_lineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 103 "CSources/PrlcLexer.l"
;
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 105 "CSources/PrlcLexer.l"
TOKEN(DOLLAR_FOF)
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 106 "CSources/PrlcLexer.l"
TOKEN(DOLLAR_FOT)
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 107 "CSources/PrlcLexer.l"
TOKEN(DOLLAR_CNF)
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 109 "CSources/PrlcLexer.l"
TOKEN(FOF)
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 110 "CSources/PrlcLexer.l"
TOKEN(CNF)
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 111 "CSources/PrlcLexer.l"
TOKEN(INCLUDE)
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 113 "CSources/PrlcLexer.l"
TOKEN(DESCRIPTION)
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 114 "CSources/PrlcLexer.l"
TOKEN(IQUOTE)
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 115 "CSources/PrlcLexer.l"
TOKEN(INFIX_INEQUALITY)
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 117 "CSources/PrlcLexer.l"
TSTRING(SINGLE_QUOTED)
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 118 "CSources/PrlcLexer.l"
TSTRING(DISTINCT_OBJECT)
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 119 "CSources/PrlcLexer.l"
TSTRING(DOLLAR_WORD)
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 120 "CSources/PrlcLexer.l"
TSTRING(DOLLAR_DOLLAR_WORD)
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 121 "CSources/PrlcLexer.l"
TSTRING(LOWER_WORD)
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 122 "CSources/PrlcLexer.l"
TSTRING(UPPER_WORD)
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 124 "CSources/PrlcLexer.l"
TINTEGER
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 125 "CSources/PrlcLexer.l"
TRATIONAL
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 126 "CSources/PrlcLexer.l"
TREAL
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 128 "CSources/PrlcLexer.l"
TOKEN(IFF)
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 129 "CSources/PrlcLexer.l"
TOKEN(IMPLY)
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 130 "CSources/PrlcLexer.l"
TOKEN(YLPMI)
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 131 "CSources/PrlcLexer.l"
TOKEN(NIFF)
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 132 "CSources/PrlcLexer.l"
TOKEN(NOR)
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 133 "CSources/PrlcLexer.l"
TOKEN(NAND)
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 135 "CSources/PrlcLexer.l"
TOKEN(GENTZEN_ARROW)
	YY_BREAK
case 27:
#line 138 "CSources/PrlcLexer.l"
case 28:
#line 139 "CSources/PrlcLexer.l"
case 29:
#line 140 "CSources/PrlcLexer.l"
case 30:
#line 141 "CSources/PrlcLexer.l"
case 31:
#line 142 "CSources/PrlcLexer.l"
case 32:
#line 143 "CSources/PrlcLexer.l"
case 33:
#line 144 "CSources/PrlcLexer.l"
case 34:
#line 145 "CSources/PrlcLexer.l"
case 35:
#line 146 "CSources/PrlcLexer.l"
case 36:
#line 147 "CSources/PrlcLexer.l"
case 37:
#line 148 "CSources/PrlcLexer.l"
case 38:
#line 149 "CSources/PrlcLexer.l"
case 39:
#line 150 "CSources/PrlcLexer.l"
case 40:
#line 151 "CSources/PrlcLexer.l"
case 41:
#line 152 "CSources/PrlcLexer.l"
case 42:
#line 153 "CSources/PrlcLexer.l"
case 43:
#line 154 "CSources/PrlcLexer.l"
case 44:
#line 155 "CSources/PrlcLexer.l"
case 45:
#line 156 "CSources/PrlcLexer.l"
case 46:
#line 157 "CSources/PrlcLexer.l"
case 47:
YY_RULE_SETUP
#line 157 "CSources/PrlcLexer.l"
{ return prlc_text[0]; }
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 159 "CSources/PrlcLexer.l"
;	/* ignore */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 161 "CSources/PrlcLexer.l"
TSTRING(NOT_A_TOKEN)
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 163 "CSources/PrlcLexer.l"
ECHO;
	YY_BREAK
#line 1107 "lex.prlc_.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed prlc_in at a new source and called
			 * prlc_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = prlc_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( prlc_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * prlc_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of prlc_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					prlc_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			prlc_restart(prlc_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) prlc_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 132 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 132 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 131);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					prlc_restart(prlc_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( prlc_wrap( ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve prlc_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    prlc_lineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void prlc_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        prlc_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            prlc__create_buffer(prlc_in,YY_BUF_SIZE );
	}

	prlc__init_buffer(YY_CURRENT_BUFFER,input_file );
	prlc__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void prlc__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		prlc_pop_buffer_state();
	 *		prlc_push_buffer_state(new_buffer);
     */
	prlc_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	prlc__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (prlc_wrap()) processing, but the only time this flag
	 * is looked at is after prlc_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void prlc__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	prlc_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE prlc__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) prlc_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in prlc__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) prlc_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in prlc__create_buffer()" );

	b->yy_is_our_buffer = 1;

	prlc__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with prlc__create_buffer()
 * 
 */
    void prlc__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		prlc_free((void *) b->yy_ch_buf  );

	prlc_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a prlc_restart() or at EOF.
 */
    static void prlc__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	prlc__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then prlc__init_buffer was _probably_
     * called from prlc_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void prlc__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		prlc__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void prlc_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	prlc_ensure_buffer_stack();

	/* This block is copied from prlc__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from prlc__switch_to_buffer. */
	prlc__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void prlc_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	prlc__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		prlc__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void prlc_ensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)prlc_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in prlc_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)prlc_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in prlc_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE prlc__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) prlc_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in prlc__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	prlc__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to prlc_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       prlc__scan_bytes() instead.
 */
YY_BUFFER_STATE prlc__scan_string (yyconst char * yystr )
{
    
	return prlc__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to prlc_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE prlc__scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) prlc_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in prlc__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = prlc__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in prlc__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up prlc_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		prlc_text[prlc_leng] = (yy_hold_char); \
		(yy_c_buf_p) = prlc_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		prlc_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int prlc_get_lineno  (void)
{
        
    return prlc_lineno;
}

/** Get the input stream.
 * 
 */
FILE *prlc_get_in  (void)
{
        return prlc_in;
}

/** Get the output stream.
 * 
 */
FILE *prlc_get_out  (void)
{
        return prlc_out;
}

/** Get the length of the current token.
 * 
 */
yy_size_t prlc_get_leng  (void)
{
        return prlc_leng;
}

/** Get the current token.
 * 
 */

char *prlc_get_text  (void)
{
        return prlc_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void prlc_set_lineno (int  line_number )
{
    
    prlc_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see prlc__switch_to_buffer
 */
void prlc_set_in (FILE *  in_str )
{
        prlc_in = in_str ;
}

void prlc_set_out (FILE *  out_str )
{
        prlc_out = out_str ;
}

int prlc_get_debug  (void)
{
        return prlc__flex_debug;
}

void prlc_set_debug (int  bdebug )
{
        prlc__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from prlc_lex_destroy(), so don't allocate here.
     */

    /* We do not touch prlc_lineno unless the option is enabled. */
    prlc_lineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    prlc_in = stdin;
    prlc_out = stdout;
#else
    prlc_in = (FILE *) 0;
    prlc_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * prlc_lex_init()
     */
    return 0;
}

/* prlc_lex_destroy is for both reentrant and non-reentrant scanners. */
int prlc_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		prlc__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		prlc_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	prlc_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * prlc_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *prlc_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *prlc_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void prlc_free (void * ptr )
{
	free( (char *) ptr );	/* see prlc_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 163 "CSources/PrlcLexer.l"





